project_name: OpenSSL_bio_enc_test
test_framework: CustomTest
bitcode_file_list: /opt/mull/openssl/openssl/bio_enc_test.bitcode.list
fork: enabled
dry_run: disabled
fail_fast: enabled
use_cache: yes
cache_directory: /opt/mull/openssl/bio_enc_test_cache
timeout: 10000
exclude_locations:
  - testutil
mutators:
  - default

custom_tests:
  - name: test_bio_enc_aes_128_cbc
    method: test_bio_enc_aes_128_cbc
    program: bio_enc_test
    arguments: [ test_bio_enc_aes_128_cbc ]

  - name: test_bio_enc_aes_128_ctr
    method: test_bio_enc_aes_128_ctr
    program: bio_enc_test
    arguments: [ test_bio_enc_aes_128_ctr ]

  - name: test_bio_enc_aes_256_cfb
    method: test_bio_enc_aes_256_cfb
    program: test_char
    arguments: [ test_bio_enc_aes_256_cfb ]

  - name: test_bio_enc_aes_256_ofb
    method: test_bio_enc_aes_256_ofb
    program: bio_enc_test
    arguments: [ test_bio_enc_aes_256_ofb ]

  - name: test_bio_enc_chacha20
    method: test_bio_enc_chacha20
    program: bio_enc_test
    arguments: [ test_bio_enc_chacha20 ]

  - name: test_bio_enc_chacha20_poly1305
    method: test_bio_enc_chacha20_poly1305
    program: bio_enc_test
    arguments: [ test_bio_enc_chacha20_poly1305 ]

