#fork: false
fork: true
project_name: OpenSSL_packettest
# max_distance: 1
dry_run: false
cache_directory: /usr/local/LLVM/mull_cache
use_cache: false
test_framework: CustomTest
bitcode_file_list: /Users/alexdenisov/Projects/OpenSSL/openssl/packettest.bitcode.list
timeout: 10000
exclude_locations:
  - testutil
diagnostics: false
mutation_operators:
  - all
custom_tests:
  - name: test_PACKET_buf_init
    method: test_PACKET_buf_init
    program: packettest
    arguments: [ test_PACKET_buf_init ]

  - name: test_PACKET_null_init
    method: test_PACKET_null_init
    program: packettest
    arguments: [ test_PACKET_null_init ]

  - name: test_PACKET_remaining
    method: test_PACKET_remaining
    program: packettest
    arguments: [ test_PACKET_remaining ]

  # This one is failing
  # - name: test_PACKET_end
  #   method: test_PACKET_end
  #   program: packettest
  #   arguments: [ test_PACKET_end ]

  - name: test_PACKET_equal
    method: test_PACKET_equal
    program: packettest
    arguments: [ test_PACKET_equal ]

  - name: test_PACKET_get_1
    method: test_PACKET_get_1
    program: packettest
    arguments: [ test_PACKET_get_1 ]

  - name: test_PACKET_get_4
    method: test_PACKET_get_4
    program: packettest
    arguments: [ test_PACKET_get_4 ]

  - name: test_PACKET_get_net_2
    method: test_PACKET_get_net_2
    program: packettest
    arguments: [ test_PACKET_get_net_2 ]

  - name: test_PACKET_get_net_3
    method: test_PACKET_get_net_3
    program: packettest
    arguments: [ test_PACKET_get_net_3 ]

  - name: test_PACKET_get_net_4
    method: test_PACKET_get_net_4
    program: packettest
    arguments: [ test_PACKET_get_net_4 ]

  - name: test_PACKET_get_sub_packet
    method: test_PACKET_get_sub_packet
    program: packettest
    arguments: [ test_PACKET_get_sub_packet ]

  - name: test_PACKET_get_bytes
    method: test_PACKET_get_bytes
    program: packettest
    arguments: [ test_PACKET_get_bytes ]

  - name: test_PACKET_copy_bytes
    method: test_PACKET_copy_bytes
    program: packettest
    arguments: [ test_PACKET_copy_bytes ]

  - name: test_PACKET_copy_all
    method: test_PACKET_copy_all
    program: packettest
    arguments: [ test_PACKET_copy_all ]

  - name: test_PACKET_memdup
    method: test_PACKET_memdup
    program: packettest
    arguments: [ test_PACKET_memdup ]

  - name: test_PACKET_strndup
    method: test_PACKET_strndup
    program: packettest
    arguments: [ test_PACKET_strndup ]

  - name: test_PACKET_contains_zero_byte
    method: test_PACKET_contains_zero_byte
    program: packettest
    arguments: [ test_PACKET_contains_zero_byte ]

  - name: test_PACKET_forward
    method: test_PACKET_forward
    program: packettest
    arguments: [ test_PACKET_forward ]

  - name: test_PACKET_get_length_prefixed_1
    method: test_PACKET_get_length_prefixed_1
    program: packettest
    arguments: [ test_PACKET_get_length_prefixed_1 ]

  - name: test_PACKET_get_length_prefixed_2
    method: test_PACKET_get_length_prefixed_2
    program: packettest
    arguments: [ test_PACKET_get_length_prefixed_2 ]

  - name: test_PACKET_get_length_prefixed_3
    method: test_PACKET_get_length_prefixed_3
    program: packettest
    arguments: [ test_PACKET_get_length_prefixed_3 ]

  - name: test_PACKET_as_length_prefixed_1
    method: test_PACKET_as_length_prefixed_1
    program: packettest
    arguments: [ test_PACKET_as_length_prefixed_1 ]

  - name: test_PACKET_as_length_prefixed_2
    method: test_PACKET_as_length_prefixed_2
    program: packettest
    arguments: [ test_PACKET_as_length_prefixed_2 ]

